#!/bin/bash
# BQ Studio Environment Setup Helper
# This script helps configure .env from FictionLab's configuration

set -e

echo "🔧 BQ Studio Environment Setup"
echo "================================"
echo ""

# Paths
MCP_SERVERS_ENV="../MCP-Writing-Servers/.env"
MCP_WEB_CONFIG=".claude/mcp-web.json"
BQ_STUDIO_ENV=".env"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if MCP-Writing-Servers/.env exists
if [ ! -f "$MCP_SERVERS_ENV" ]; then
    echo -e "${RED}❌ Error: Could not find $MCP_SERVERS_ENV${NC}"
    echo ""
    echo "Please ensure MCP-Writing-Servers repository is in the same parent directory:"
    echo "  RYALS/"
    echo "  ├── MCP-Writing-Servers/"
    echo "  │   └── .env"
    echo "  └── BQ-Studio/"
    echo "      └── setup-env.sh (this script)"
    exit 1
fi

echo -e "${GREEN}✓ Found MCP-Writing-Servers/.env${NC}"

# Extract values from MCP-Writing-Servers/.env
echo ""
echo "📋 Reading configuration from MCP-Writing-Servers..."

# Function to extract value from .env file
extract_value() {
    grep "^$1=" "$MCP_SERVERS_ENV" | cut -d'=' -f2- | tr -d '"' | tr -d "'"
}

DATABASE_URL=$(extract_value "DATABASE_URL")
MCP_AUTH_TOKEN=$(extract_value "MCP_AUTH_TOKEN")
POSTGRES_USER=$(extract_value "POSTGRES_USER")
POSTGRES_PASSWORD=$(extract_value "POSTGRES_PASSWORD")
POSTGRES_DB=$(extract_value "POSTGRES_DB")
PGBOUNCER_PORT=$(extract_value "PGBOUNCER_PORT")

# Defaults if not found
PGBOUNCER_PORT=${PGBOUNCER_PORT:-6432}
POSTGRES_DB=${POSTGRES_DB:-fictionlab}

echo -e "${GREEN}✓ Extracted database configuration${NC}"

# Check which mode (local or tunnels)
echo ""
echo "🌐 Connection Mode Selection"
echo "----------------------------"
echo "1) Local Development (localhost:3001-3009) - Recommended"
echo "2) Cloudflare Tunnels (for Claude Code Web)"
echo ""
read -p "Select mode [1]: " MODE
MODE=${MODE:-1}

# Start building .env file
echo ""
echo "📝 Creating .env file..."

cat > "$BQ_STUDIO_ENV" <<EOF
# BQ Studio - Environment Configuration
# Auto-generated by setup-env.sh on $(date)
# Source: MCP-Writing-Servers/.env

# ============================================
# Database Connection (from MCP-Writing-Servers)
# ============================================
DATABASE_URL=${DATABASE_URL}
PGBOUNCER_HOST=localhost
PGBOUNCER_PORT=${PGBOUNCER_PORT}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ============================================
# MCP Authentication (from MCP-Writing-Servers)
# ============================================
MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}

EOF

if [ "$MODE" = "2" ]; then
    # Tunnel mode - extract URLs from mcp-web.json
    echo "# ============================================" >> "$BQ_STUDIO_ENV"
    echo "# MCP Server URLs (Cloudflare Tunnels)" >> "$BQ_STUDIO_ENV"
    echo "# ============================================" >> "$BQ_STUDIO_ENV"
    echo "# Extracted from .claude/mcp-web.json" >> "$BQ_STUDIO_ENV"

    if [ -f "$MCP_WEB_CONFIG" ]; then
        # Extract tunnel URLs from mcp-web.json
        # This is a simple extraction - adjust if your JSON structure is different

        echo "MCP_AUTHOR_SERVER_URL=$(grep -A1 '"author-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_SERIES_PLANNING_SERVER_URL=$(grep -A1 '"series-planning-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_BOOK_PLANNING_SERVER_URL=$(grep -A1 '"book-planning-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_CHAPTER_PLANNING_SERVER_URL=$(grep -A1 '"chapter-planning-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_CHARACTER_PLANNING_SERVER_URL=$(grep -A1 '"character-planning-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_SCENE_SERVER_URL=$(grep -A1 '"scene-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_CORE_CONTINUITY_SERVER_URL=$(grep -A1 '"core-continuity-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_REVIEW_SERVER_URL=$(grep -A1 '"review-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"
        echo "MCP_REPORTING_SERVER_URL=$(grep -A1 '"reporting-server"' "$MCP_WEB_CONFIG" | grep '"url"' | cut -d'"' -f4)" >> "$BQ_STUDIO_ENV"

        echo -e "${GREEN}✓ Extracted tunnel URLs from mcp-web.json${NC}"
    else
        echo -e "${YELLOW}⚠ mcp-web.json not found. You'll need to run tunnels first.${NC}"
        echo "# MCP_AUTHOR_SERVER_URL=https://xxxxx.trycloudflare.com" >> "$BQ_STUDIO_ENV"
        echo "# MCP_SERIES_PLANNING_SERVER_URL=https://xxxxx.trycloudflare.com" >> "$BQ_STUDIO_ENV"
        echo "# ... etc (run start-cloudflare-tunnels.sh first)" >> "$BQ_STUDIO_ENV"
    fi
else
    # Local mode - use localhost URLs
    echo "# ============================================" >> "$BQ_STUDIO_ENV"
    echo "# MCP Server URLs (Local Development)" >> "$BQ_STUDIO_ENV"
    echo "# ============================================" >> "$BQ_STUDIO_ENV"
    echo "# Using localhost - FictionLab must be running" >> "$BQ_STUDIO_ENV"

    cat >> "$BQ_STUDIO_ENV" <<EOF
MCP_AUTHOR_SERVER_URL=http://localhost:3001
MCP_SERIES_PLANNING_SERVER_URL=http://localhost:3002
MCP_BOOK_PLANNING_SERVER_URL=http://localhost:3003
MCP_CHAPTER_PLANNING_SERVER_URL=http://localhost:3004
MCP_CHARACTER_PLANNING_SERVER_URL=http://localhost:3005
MCP_SCENE_SERVER_URL=http://localhost:3006
MCP_CORE_CONTINUITY_SERVER_URL=http://localhost:3007
MCP_REVIEW_SERVER_URL=http://localhost:3008
MCP_REPORTING_SERVER_URL=http://localhost:3009

# Database Admin Interface
MCP_DB_ADMIN_URL=http://localhost:3010
EOF
    echo -e "${GREEN}✓ Configured for local development${NC}"
fi

# Add API keys section
cat >> "$BQ_STUDIO_ENV" <<EOF

# ============================================
# AI Service Configuration
# ============================================
# TODO: Add your API keys below
ANTHROPIC_API_KEY=your-anthropic-key-here
OPENAI_API_KEY=your-openai-key-here

# ============================================
# Application Settings
# ============================================
NODE_ENV=development
LOG_LEVEL=info
EOF

echo ""
echo -e "${GREEN}✅ .env file created successfully!${NC}"
echo ""
echo "📋 Next steps:"
echo "1. Edit .env and add your API keys:"
echo "   - ANTHROPIC_API_KEY (required for Writing Team)"
echo "   - OPENAI_API_KEY (optional)"
echo ""

if [ "$MODE" = "1" ]; then
    echo "2. Make sure FictionLab is running:"
    echo "   - Launch from Start Menu, OR"
    echo "   - cd ../MCP-Electron-App && npm start"
    echo ""
    echo "3. Test connection:"
    echo "   curl http://localhost:3001/health"
else
    echo "2. Make sure Cloudflare tunnels are running:"
    echo "   ./start-cloudflare-tunnels.sh"
    echo ""
    echo "3. Update .env with actual tunnel URLs from mcp-web.json"
fi

echo ""
echo "4. Start BQ Studio:"
echo "   npm run dev"
echo ""

# Offer to test connections
if [ "$MODE" = "1" ]; then
    echo ""
    read -p "🔍 Test MCP server connections now? [y/N]: " TEST_CONN
    if [ "$TEST_CONN" = "y" ] || [ "$TEST_CONN" = "Y" ]; then
        echo ""
        echo "Testing MCP server connections..."
        for port in {3001..3009}; do
            if curl -s -o /dev/null -w "%{http_code}" "http://localhost:$port/health" | grep -q "200"; then
                echo -e "${GREEN}✓ localhost:$port - OK${NC}"
            else
                echo -e "${RED}✗ localhost:$port - NOT RESPONDING${NC}"
            fi
        done
        echo ""
        echo -e "${YELLOW}Note: If servers aren't responding, launch FictionLab first.${NC}"
    fi
fi

echo ""
echo -e "${GREEN}Setup complete! 🎉${NC}"
