# BQ Studio Environment Setup Helper (Windows PowerShell)
# This script helps configure .env from FictionLab's configuration

Write-Host "[BQ Studio Environment Setup]" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Paths
$McpServersEnv = "..\MCP-Writing-Servers\.env"
$McpWebConfig = ".claude\mcp-web.json"
$BqStudioEnv = ".env"

# Check if .env already exists
if (Test-Path $BqStudioEnv) {
    Write-Host "WARNING: .env file already exists!" -ForegroundColor Yellow
    Write-Host ""
    $overwrite = Read-Host "Do you want to OVERWRITE your existing .env file? [y/N]"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host ""
        Write-Host "Setup cancelled. Your existing .env file was not modified." -ForegroundColor Green
        Write-Host ""
        Write-Host "If you need to update specific values:"
        Write-Host "1. Edit .env manually, OR"
        Write-Host "2. Backup your .env and run this script again"
        exit 0
    }
    Write-Host ""
    Write-Host "Creating backup: .env.backup" -ForegroundColor Yellow
    Copy-Item $BqStudioEnv "$BqStudioEnv.backup" -Force
    Write-Host "Backup created. Proceeding with setup..." -ForegroundColor Green
    Write-Host ""
}

# Check if MCP-Writing-Servers/.env exists
if (-not (Test-Path $McpServersEnv)) {
    Write-Host "[ERROR] Could not find $McpServersEnv" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please ensure MCP-Writing-Servers repository is in the same parent directory:"
    Write-Host "  RYALS\"
    Write-Host "  ├── MCP-Writing-Servers\"
    Write-Host "  │   └── .env"
    Write-Host "  └── BQ-Studio\"
    Write-Host "      └── setup-env.ps1 (this script)"
    exit 1
}

Write-Host "[OK] Found MCP-Writing-Servers\.env" -ForegroundColor Green

# Extract values from MCP-Writing-Servers/.env
Write-Host ""
Write-Host "Reading configuration from MCP-Writing-Servers..." -ForegroundColor Cyan

$envContent = Get-Content $McpServersEnv

function Extract-Value {
    param($Key)
    $line = $envContent | Where-Object { $_ -match "^$Key=" } | Select-Object -First 1
    if ($line) {
        $value = $line -replace "^$Key=", ""
        $value = $value -replace '^"', '' -replace '"$', ''
        $value = $value -replace "^'", '' -replace "'$", ''
        return $value
    }
    return $null
}

$DatabaseUrl = Extract-Value "DATABASE_URL"
$McpAuthToken = Extract-Value "MCP_AUTH_TOKEN"
$PostgresUser = Extract-Value "POSTGRES_USER"
$PostgresPassword = Extract-Value "POSTGRES_PASSWORD"
$PostgresDb = Extract-Value "POSTGRES_DB"
$PgBouncerPort = Extract-Value "PGBOUNCER_PORT"

# Defaults if not found
if (-not $PgBouncerPort) { $PgBouncerPort = "6432" }
if (-not $PostgresDb) { $PostgresDb = "fictionlab" }

Write-Host "[OK] Extracted database configuration" -ForegroundColor Green

# Check which mode (local or tunnels)
Write-Host ""
Write-Host "Connection Mode Selection" -ForegroundColor Cyan
Write-Host "----------------------------"
Write-Host "1) Local Development (localhost:3001-3009) - Recommended"
Write-Host "2) Cloudflare Tunnels (for Claude Code Web)"
Write-Host ""
$mode = Read-Host "Select mode [1]"
if (-not $mode) { $mode = "1" }

# Start building .env file
Write-Host ""
Write-Host "Creating .env file..." -ForegroundColor Cyan

$envFileContent = @"
# BQ Studio - Environment Configuration
# Auto-generated by setup-env.ps1 on $(Get-Date)
# Source: MCP-Writing-Servers/.env

# ============================================
# Database Connection (from MCP-Writing-Servers)
# ============================================
DATABASE_URL=$DatabaseUrl
PGBOUNCER_HOST=localhost
PGBOUNCER_PORT=$PgBouncerPort
POSTGRES_DB=$PostgresDb
POSTGRES_USER=$PostgresUser
POSTGRES_PASSWORD=$PostgresPassword

# ============================================
# MCP Authentication (from MCP-Writing-Servers)
# ============================================
MCP_AUTH_TOKEN=$McpAuthToken

"@

if ($mode -eq "2") {
    # Tunnel mode - extract URLs from mcp-web.json
    $envFileContent += @"
# ============================================
# MCP Server URLs (Cloudflare Tunnels)
# ============================================
# Extracted from .claude/mcp-web.json

"@

    if (Test-Path $McpWebConfig) {
        $mcpConfig = Get-Content $McpWebConfig -Raw | ConvertFrom-Json

        # Extract URLs from mcp-web.json
        $envFileContent += "MCP_AUTHOR_SERVER_URL=$($mcpConfig.'author-server'.url)`n"
        $envFileContent += "MCP_SERIES_PLANNING_SERVER_URL=$($mcpConfig.'series-planning-server'.url)`n"
        $envFileContent += "MCP_BOOK_PLANNING_SERVER_URL=$($mcpConfig.'book-planning-server'.url)`n"
        $envFileContent += "MCP_CHAPTER_PLANNING_SERVER_URL=$($mcpConfig.'chapter-planning-server'.url)`n"
        $envFileContent += "MCP_CHARACTER_PLANNING_SERVER_URL=$($mcpConfig.'character-planning-server'.url)`n"
        $envFileContent += "MCP_SCENE_SERVER_URL=$($mcpConfig.'scene-server'.url)`n"
        $envFileContent += "MCP_CORE_CONTINUITY_SERVER_URL=$($mcpConfig.'core-continuity-server'.url)`n"
        $envFileContent += "MCP_REVIEW_SERVER_URL=$($mcpConfig.'review-server'.url)`n"
        $envFileContent += "MCP_REPORTING_SERVER_URL=$($mcpConfig.'reporting-server'.url)`n"

        Write-Host "[OK] Extracted tunnel URLs from mcp-web.json" -ForegroundColor Green
    } else {
        Write-Host "[WARNING] mcp-web.json not found. You'll need to run tunnels first." -ForegroundColor Yellow
        $envFileContent += "# MCP_AUTHOR_SERVER_URL=https://xxxxx.trycloudflare.com`n"
        $envFileContent += "# MCP_SERIES_PLANNING_SERVER_URL=https://xxxxx.trycloudflare.com`n"
        $envFileContent += "# ... etc (run start-cloudflare-tunnels.ps1 first)`n"
    }
} else {
    # Local mode - use localhost URLs
    $envFileContent += @"
# ============================================
# MCP Server URLs (Local Development)
# ============================================
# Using localhost - FictionLab must be running
MCP_AUTHOR_SERVER_URL=http://localhost:3001
MCP_SERIES_PLANNING_SERVER_URL=http://localhost:3002
MCP_BOOK_PLANNING_SERVER_URL=http://localhost:3003
MCP_CHAPTER_PLANNING_SERVER_URL=http://localhost:3004
MCP_CHARACTER_PLANNING_SERVER_URL=http://localhost:3005
MCP_SCENE_SERVER_URL=http://localhost:3006
MCP_CORE_CONTINUITY_SERVER_URL=http://localhost:3007
MCP_REVIEW_SERVER_URL=http://localhost:3008
MCP_REPORTING_SERVER_URL=http://localhost:3009

# Database Admin Interface
MCP_DB_ADMIN_URL=http://localhost:3010

"@
    Write-Host "[OK] Configured for local development" -ForegroundColor Green
}

# Add API keys section
$envFileContent += @"
# ============================================
# AI Service Configuration
# ============================================
# TODO: Add your API keys below
ANTHROPIC_API_KEY=your-anthropic-key-here
OPENAI_API_KEY=your-openai-key-here

# ============================================
# Application Settings
# ============================================
NODE_ENV=development
LOG_LEVEL=info
"@

# Write to file
$envFileContent | Out-File -FilePath $BqStudioEnv -Encoding UTF8

Write-Host ""
Write-Host "[SUCCESS] .env file created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Edit .env and add your API keys:"
Write-Host "   - ANTHROPIC_API_KEY (required for Writing Team)"
Write-Host "   - OPENAI_API_KEY (optional)"
Write-Host ""

if ($mode -eq "1") {
    Write-Host "2. Make sure FictionLab is running:"
    Write-Host "   - Launch from Start Menu, OR"
    Write-Host "   - cd ..\MCP-Electron-App; npm start"
    Write-Host ""
    Write-Host "3. Test connection:"
    Write-Host "   curl http://localhost:3001/health"
} else {
    Write-Host "2. Make sure Cloudflare tunnels are running:"
    Write-Host "   .\start-cloudflare-tunnels.ps1"
    Write-Host ""
    Write-Host "3. Update .env with actual tunnel URLs from mcp-web.json"
}

Write-Host ""
Write-Host "4. Start BQ Studio:"
Write-Host "   npm run dev"
Write-Host ""

# Offer to test connections
if ($mode -eq "1") {
    Write-Host ""
    $testConn = Read-Host "Test MCP server connections now? [y/N]"
    if ($testConn -eq "y" -or $testConn -eq "Y") {
        Write-Host ""
        Write-Host "Testing MCP server connections..." -ForegroundColor Cyan

        for ($port = 3001; $port -le 3009; $port++) {
            try {
                $response = Invoke-WebRequest -Uri "http://localhost:$port/health" -Method Get -TimeoutSec 2 -UseBasicParsing
                if ($response.StatusCode -eq 200) {
                    Write-Host "[OK] localhost:$port - RESPONDING" -ForegroundColor Green
                }
            } catch {
                Write-Host "[FAIL] localhost:$port - NOT RESPONDING" -ForegroundColor Red
            }
        }

        Write-Host ""
        Write-Host "Note: If servers aren't responding, launch FictionLab first." -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
